export * from './social-icons'
export * from './whoWeAre'
export * from './cover'
export * from './whatWeDo'
export * from './navbar'
export * from './illustration'
export * from './news'
export * from './gallery'
export * from './donate'
export * from './projects'
export * from './operating-mode'
export * from './footer'
export * from './aboutUs'
export * from './newsPageData'
// Google Forms
export * from './donateGoogleForm'
export * from './joinGoogleForm'
export * from './requestGoogleForm'
export * from './visitGoogleForm'
// Pages
export * from './HomePage'
export * from './AboutUsPage'
export * from './NewsPage'


export * from './pages/aboutUs'
